spring:
  jpa:
    hibernate:
      ddl-auto: update
      default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
server:
  port: ${PORT:8080}
logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.postgresql: DEBUG